import type { PodcasterDetailsUI } from "../types/podcaster";
import type { ShowUI } from "../types/show";

export const mockPodcasterDetails: PodcasterDetailsUI = {
  AccountId: 17,
  Name: "Hoàng Minh Lộc",
  AverageRating: 5,
  Description: `<p>
    Hoàng Minh Lộc luôn được biết đến là một giọng nói vàng trong làng podcast.
</p>
<p>
    Các audio của anh ấy luôn được mọi người gọi là “<i><strong>Bản Tình Ca Của Biến</strong></i>” vì chất giọng du dương tựa<strong> sóng</strong>.
</p>
<p>
    &nbsp;
</p>`,
  ImageUrl:
    "https://i.pinimg.com/736x/d8/39/af/d839affe7abace590b5a6b887320dda5.jpg",
  IsBuddy: true,
  IsFollowedByCurrentUser: false,
  IsVerified: true,
  ListenCount: 12000000,
  RatingCount: 3,
  ReviewList: [
    {
      Rating: 5,
      Account: {
        Id: 1,
        Email: "soryzzmikely@gmail.com",
        FullName: "Lộc Hoàng",
        ImageUrl: "",
      },
      Title: "Podcaster Siêu Đẹp Trai",
      Content:
        "Nói sao nhỉ, anh ta lôi cuốn tôi từ những giây đầu tiên. Giọng anh ấy khiến tôi móc cả đêm!",
      Id: "1",
      DeletedAt: "",
      UpdatedAt: "",
    },
    {
      Rating: 5,
      Account: {
        Id: 1,
        Email: "soryzzmikely@gmail.com",
        FullName: "Lộc Hoàng",
        ImageUrl: "",
      },
      Title: "Podcaster Siêu Đẹp Trai",
      Content:
        "Nói sao nhỉ, anh ta lôi cuốn tôi từ những giây đầu tiên. Giọng anh ấy khiến tôi móc cả đêm!",
      Id: "2",
      DeletedAt: "",
      UpdatedAt: "",
    },
    {
      Rating: 5,
      Account: {
        Id: 1,
        Email: "soryzzmikely@gmail.com",
        FullName: "Lộc Hoàng",
        ImageUrl: "",
      },
      Title: "Podcaster Siêu Đẹp Trai",
      Content:
        "Nói sao nhỉ, anh ta lôi cuốn tôi từ những giây đầu tiên. Giọng anh ấy khiến tôi móc cả đêm!",
      Id: "3",
      DeletedAt: "",
      UpdatedAt: "",
    },
  ],
  TotalFollow: 1200,
  VerifiedAt: "",
};

export const mockShows: { ShowList: ShowUI[] } = {
  ShowList: [
    // ========= CATEGORY: PARANORMAL =========
    {
      Id: "show-001",
      Name: "Lời Thì Thầm Trong Đêm",
      Description: "Những câu chuyện ma ám dựa trên lời kể có thật.",
      AverageRating: 4.8,
      Copyright: "",
      EpisodeCount: 24,
      ImageUrl:
        "https://i.pinimg.com/1200x/15/83/fc/1583fcc6dd139b1588e65964452b4d2f.jpg",
      Hashtags: [{ Id: 1, Name: "paranormal" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 129000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "101", ImageUrl: "", Name: "Night Whisper" },
      Podcaster: { Email: "", FullName: "Nguyễn Shadow", Id: 1, ImageUrl: "" },
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      RatingCount: 3200,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 8200,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-002",
      Name: "Hộp Thư Âm Giữa Rừng",
      Description: "Mỗi lá thư là một bí ẩn bị chôn vùi dưới tán cây già.",
      AverageRating: 4.7,
      Copyright: "",
      EpisodeCount: 18,
      ImageUrl:
        "https://i.pinimg.com/736x/8d/76/cc/8d76cc5e5165d7dad5e52b2db76c3857.jpg",
      Hashtags: [{ Id: 2, Name: "forest" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 88000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "102", ImageUrl: "", Name: "Forest Echo" },
      Podcaster: { Email: "", FullName: "Linh Dark", Id: 2, ImageUrl: "" },
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      RatingCount: 2100,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 7300,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "2 Times A Week",
    },

    {
      Id: "show-003",
      Name: "Hành Lang Số 7",
      Description:
        "Căn phòng bị khóa 40 năm và hành lang không ai dám bước vào.",
      AverageRating: 4.9,
      Copyright: "",
      EpisodeCount: 30,
      ImageUrl:
        "https://i.pinimg.com/736x/42/22/25/422225c774e373dce653578117c58a5f.jpg",
      Hashtags: [{ Id: 3, Name: "schoolghost" }],
      CreatedAt: "",
      CurrentStatus: { Id: 2, Name: "Completed" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 152000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "101", ImageUrl: "", Name: "Night Whisper" },
      Podcaster: { Email: "", FullName: "Nguyễn Shadow", Id: 1, ImageUrl: "" },
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      RatingCount: 5600,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 9100,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    // ========= CATEGORY: DARK FOLKLORE =========
    {
      Id: "show-004",
      Name: "Truyền Thuyết Bóng Đêm",
      Description:
        "Tổng hợp những truyền thuyết dân gian Việt Nam theo góc nhìn đen tối.",
      AverageRating: 4.6,
      Copyright: "",
      EpisodeCount: 20,
      ImageUrl:
        "https://i.pinimg.com/736x/4f/59/75/4f597506ffb6bb72c80d2819dc64bc6a.jpg",
      Hashtags: [{ Id: 4, Name: "folklore" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 65000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "103", ImageUrl: "", Name: "Folk Horror" },
      Podcaster: { Email: "", FullName: "Hải Midnight", Id: 3, ImageUrl: "" },
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      RatingCount: 1700,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 4200,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-005",
      Name: "Bùa Ngải Và Huyết Ấn",
      Description: "Những câu chuyện tâm linh liên quan bùa chú Đông Nam Á.",
      AverageRating: 4.8,
      Copyright: "",
      EpisodeCount: 15,
      ImageUrl:
        "https://i.pinimg.com/736x/ee/74/00/ee740051dc9a35c2041dcb6f92e58936.jpg",
      Hashtags: [{ Id: 5, Name: "ritual" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 98000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "103", ImageUrl: "", Name: "Folk Horror" },
      Podcaster: { Email: "", FullName: "Hải Midnight", Id: 3, ImageUrl: "" },
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      RatingCount: 2600,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 6700,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-006",
      Name: "Ký Ức Làng Âm",
      Description: "Một ngôi làng nhỏ nhưng không ai dám nhắc tên.",
      AverageRating: 4.7,
      Copyright: "",
      EpisodeCount: 22,
      ImageUrl:
        "https://i.pinimg.com/736x/ca/91/29/ca912905045ae94502e493f9efd07de4.jpg",
      Hashtags: [{ Id: 6, Name: "village" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 54000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "104", ImageUrl: "", Name: "Night Village" },
      Podcaster: { Email: "", FullName: "Lan Raven", Id: 4, ImageUrl: "" },
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      RatingCount: 1500,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 3900,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "2 Times A Week",
    },

    // ========= CATEGORY: TRUE HORROR =========
    {
      Id: "show-007",
      Name: "Hồ Sơ Kinh Hoàng",
      Description: "Tổng hợp các vụ án rợn người từng gây ám ảnh Việt Nam.",
      AverageRating: 4.9,
      Copyright: "",
      EpisodeCount: 40,
      ImageUrl:
        "https://i.pinimg.com/736x/1c/ae/8f/1cae8f6e1c741e5f63a9eb1baeb7f9c8.jpg",
      Hashtags: [{ Id: 7, Name: "crime" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 210000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "105", ImageUrl: "", Name: "True Fear" },
      Podcaster: { Email: "", FullName: "Minh Cold", Id: 5, ImageUrl: "" },
      PodcastSubCategory: { Id: 30, Name: "True Horror", PodcastCategoryId: 1 },
      RatingCount: 8700,
      PodcastShowSubscriptionType: { Id: 2, Name: "Premium" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 15400,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-008",
      Name: "Bằng Chứng Âm",
      Description: "Những cuộc ghi âm thật sự khiến người nghe lạnh gáy.",
      AverageRating: 4.8,
      EpisodeCount: 28,
      Copyright: "",
      ImageUrl:
        "https://i.pinimg.com/736x/52/2a/48/522a48179379130cf4ba1d37a7bc398a.jpg",
      Hashtags: [{ Id: 8, Name: "recordings" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 132000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "105", ImageUrl: "", Name: "True Fear" },
      Podcaster: { Email: "", FullName: "Minh Cold", Id: 5, ImageUrl: "" },
      PodcastSubCategory: { Id: 30, Name: "True Horror", PodcastCategoryId: 1 },
      RatingCount: 4700,
      PodcastShowSubscriptionType: { Id: 2, Name: "Premium" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 11200,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-009",
      Name: "Nhật Ký Tử Thần",
      Description: "Từ cuốn nhật ký tìm thấy trong căn nhà bỏ hoang.",
      AverageRating: 4.6,
      EpisodeCount: 16,
      Copyright: "",
      ImageUrl:
        "https://i.pinimg.com/736x/4a/15/fe/4a15fed9893058be7f9859b9a6836916.jpg",
      Hashtags: [{ Id: 9, Name: "haunted" }],
      CreatedAt: "",
      CurrentStatus: { Id: 2, Name: "Completed" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 78000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "105", ImageUrl: "", Name: "True Fear" },
      Podcaster: { Email: "", FullName: "Minh Cold", Id: 5, ImageUrl: "" },
      PodcastSubCategory: { Id: 30, Name: "True Horror", PodcastCategoryId: 1 },
      RatingCount: 2300,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 5400,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Monthly",
    },

    // ========= CATEGORY: URBAN LEGENDS =========
    {
      Id: "show-010",
      Name: "Thành Phố Bóng Tối",
      Description: "Những truyền thuyết đô thị khiến giới trẻ rợn tóc gáy.",
      AverageRating: 4.8,
      EpisodeCount: 22,
      Copyright: "",
      ImageUrl:
        "https://i.pinimg.com/736x/31/48/78/31487879a5776c8680e4ec3a6d34743c.jpg",
      Hashtags: [{ Id: 10, Name: "urbanlegend" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 94000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "106", ImageUrl: "", Name: "Urban Tales" },
      Podcaster: { Email: "", FullName: "Kha Phantom", Id: 6, ImageUrl: "" },
      PodcastSubCategory: {
        Id: 40,
        Name: "Urban Legends",
        PodcastCategoryId: 1,
      },
      RatingCount: 3300,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 7700,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "2 Times A Week",
    },

    // — 10 items done; create 10 more fast + lighter descriptions —

    {
      Id: "show-011",
      Name: "Tầng Hầm Số 4",
      Description: "Một tầng hầm không ai còn muốn mở ra.",
      AverageRating: 4.7,
      EpisodeCount: 12,
      ImageUrl:
        "https://i.pinimg.com/736x/76/a1/a7/76a1a741f82e9f723c0b0bba93ba6744.jpg",
      Copyright: "",
      Hashtags: [{ Id: 11, Name: "basement" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 51000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastChannel: { Id: "106", ImageUrl: "", Name: "Urban Tales" },
      Podcaster: { Email: "", FullName: "Kha Phantom", Id: 6, ImageUrl: "" },
      PodcastSubCategory: {
        Id: 40,
        Name: "Urban Legends",
        PodcastCategoryId: 1,
      },
      RatingCount: 1800,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TakenDownReason: "",
      TotalFollow: 3300,
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-012",
      Name: "Chiếc Gương Không Phản Chiếu",
      Description: "Cái bóng đứng sau bạn không bao giờ biến mất.",
      AverageRating: 4.8,
      EpisodeCount: 14,
      ImageUrl:
        "https://i.pinimg.com/736x/e1/13/3c/e1133cacff211427bdd6bec32fdcb940.jpg",
      Copyright: "",
      Hashtags: [{ Id: 12, Name: "mirror" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      Podcaster: { Email: "", FullName: "Linh Dark", Id: 2, ImageUrl: "" },
      PodcastChannel: { Id: "102", ImageUrl: "", Name: "Forest Echo" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 62000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      RatingCount: 2600,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 5200,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-013",
      Name: "Người Đàn Bà Đội Mưa",
      Description: "Huyền thoại người phụ nữ xuất hiện sau 3 giờ sáng.",
      AverageRating: 4.7,
      EpisodeCount: 10,
      ImageUrl:
        "https://i.pinimg.com/736x/cf/81/60/cf816084831b35a636e596835f7aeb50.jpg",
      Copyright: "",
      Hashtags: [{ Id: 13, Name: "woman" }],
      CreatedAt: "",
      CurrentStatus: { Id: 2, Name: "Completed" },
      Podcaster: { Email: "", FullName: "Lan Raven", Id: 4, ImageUrl: "" },
      PodcastChannel: { Id: "104", ImageUrl: "", Name: "Night Village" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 44000,
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      RatingCount: 1400,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 2900,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Monthly",
    },

    {
      Id: "show-014",
      Name: "Tiếng Gõ Lúc Nửa Đêm",
      Description: "Cánh cửa gỗ cũ và những âm thanh không giải thích được.",
      AverageRating: 4.6,
      EpisodeCount: 17,
      ImageUrl:
        "https://i.pinimg.com/736x/75/4a/24/754a24006a8fc3ea09070c173621eed3.jpg",
      Copyright: "",
      Hashtags: [{ Id: 14, Name: "knocking" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      Podcaster: { Email: "", FullName: "Kha Phantom", Id: 6, ImageUrl: "" },
      PodcastChannel: { Id: "106", ImageUrl: "", Name: "Urban Tales" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 57000,
      PodcastSubCategory: {
        Id: 40,
        Name: "Urban Legends",
        PodcastCategoryId: 1,
      },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 2000,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 3600,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-015",
      Name: "Sát Nhân Trong Sương",
      Description: "Lời đồn về bóng người xuất hiện trong lớp sương dày.",
      AverageRating: 4.7,
      EpisodeCount: 21,
      ImageUrl:
        "https://i.pinimg.com/736x/02/87/08/0287084d707529522a3e11d0637162ac.jpg",
      Copyright: "",
      Hashtags: [{ Id: 15, Name: "fog" }],
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      Podcaster: { Email: "", FullName: "Minh Cold", Id: 5, ImageUrl: "" },
      PodcastChannel: { Id: "105", ImageUrl: "", Name: "True Fear" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 61000,
      PodcastSubCategory: { Id: 30, Name: "True Horror", PodcastCategoryId: 1 },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 2500,
      PodcastShowSubscriptionType: { Id: 2, Name: "Premium" },
      ReleaseDate: "",
      TotalFollow: 4100,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-016",
      Name: "Căn Phòng Không Cửa Sổ",
      Description: "Không ánh sáng, nhưng luôn có ai đó đứng ở góc phòng.",
      AverageRating: 4.8,
      EpisodeCount: 19,
      ImageUrl:
        "https://i.pinimg.com/736x/49/cd/06/49cd06dabe73cf5383f0f4bece8ac824.jpg",
      Copyright: "",
      Hashtags: [{ Id: 16, Name: "room" }],
      Podcaster: { Email: "", FullName: "Nguyễn Shadow", Id: 1, ImageUrl: "" },
      PodcastChannel: { Id: "101", ImageUrl: "", Name: "Night Whisper" },
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 69000,
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 2800,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 5300,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-017",
      Name: "Hộp Nhạc Phản Chủ",
      Description: "Mỗi lần hộp nhạc vang lên, ai đó lại biến mất.",
      AverageRating: 4.9,
      EpisodeCount: 13,
      ImageUrl:
        "https://i.pinimg.com/736x/f9/76/b3/f976b3917f6b9bcf786908f4098bf20f.jpg",
      Copyright: "",
      Hashtags: [{ Id: 17, Name: "musicbox" }],
      Podcaster: { Email: "", FullName: "Linh Dark", Id: 2, ImageUrl: "" },
      PodcastChannel: { Id: "102", ImageUrl: "", Name: "Forest Echo" },
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 87000,
      PodcastSubCategory: { Id: 10, Name: "Paranormal", PodcastCategoryId: 1 },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 3500,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 5900,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "2 Times A Week",
    },

    {
      Id: "show-018",
      Name: "Tiếng Hú Sau Đồi",
      Description: "Âm thanh ghê rợn mỗi khi mặt trời lặn.",
      AverageRating: 4.6,
      EpisodeCount: 11,
      ImageUrl:
        "https://i.pinimg.com/1200x/a8/16/67/a81667aea97f1bcb7bd4a041dbea841d.jpg",
      Copyright: "",
      Hashtags: [{ Id: 18, Name: "howl" }],
      Podcaster: { Email: "", FullName: "Lan Raven", Id: 4, ImageUrl: "" },
      PodcastChannel: { Id: "104", ImageUrl: "", Name: "Night Village" },
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 52000,
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 1600,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 3000,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Monthly",
    },

    {
      Id: "show-019",
      Name: "Đêm Không Sao",
      Description: "Một đêm trời không có sao và cũng không có ai sống sót.",
      AverageRating: 4.8,
      EpisodeCount: 14,
      ImageUrl:
        "https://i.pinimg.com/1200x/12/99/dc/1299dca6c06c854b7ffc767ff5c075d3.jpg",
      Copyright: "",
      Hashtags: [{ Id: 19, Name: "nostar" }],
      Podcaster: { Email: "", FullName: "Minh Cold", Id: 5, ImageUrl: "" },
      PodcastChannel: { Id: "105", ImageUrl: "", Name: "True Fear" },
      CreatedAt: "",
      CurrentStatus: { Id: 2, Name: "Completed" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 76000,
      PodcastSubCategory: { Id: 30, Name: "True Horror", PodcastCategoryId: 1 },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 2200,
      PodcastShowSubscriptionType: { Id: 2, Name: "Premium" },
      ReleaseDate: "",
      TotalFollow: 4800,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },

    {
      Id: "show-020",
      Name: "Nhà Hoang Cuối Đường",
      Description: "Căn nhà không ai dám sửa lại vì lời nguyền truyền đời.",
      AverageRating: 4.7,
      EpisodeCount: 18,
      ImageUrl:
        "https://i.pinimg.com/736x/8c/55/94/8c5594d646d98b2e91d16634d10b3528.jpg",
      Copyright: "",
      Hashtags: [{ Id: 20, Name: "abandoned" }],
      Podcaster: { Email: "", FullName: "Hải Midnight", Id: 3, ImageUrl: "" },
      PodcastChannel: { Id: "103", ImageUrl: "", Name: "Folk Horror" },
      CreatedAt: "",
      CurrentStatus: { Id: 1, Name: "Ongoing" },
      IsReleased: true,
      Language: "Vietnamese",
      ListenCount: 69000,
      PodcastSubCategory: {
        Id: 20,
        Name: "Dark Folklore",
        PodcastCategoryId: 1,
      },
      PodcastCategory: { Id: 1, Name: "Horror & Mystery" },
      RatingCount: 2800,
      PodcastShowSubscriptionType: { Id: 1, Name: "Free" },
      ReleaseDate: "",
      TotalFollow: 4200,
      TakenDownReason: "",
      TrailerAudioFileKey: "",
      UpdatedAt: "",
      UploadFrequency: "Weekly",
    },
  ],
};
